### PR TITLE
First Round of Changes

### PR DESCRIPTION
**Pull request by jamescrowley321**

### CODE REVIEW

**Comment by jamescrowley321** [comment]
Let me know if you have any issues.

**Comment by appakz** [comment]
I'm going to add the .vs folder to the .gitignore on the master branch then rebase this branch onto that before reviewing.

**Comment by appakz** [comment]
Also, for future reference the PR doesn't typically get merged into master until after the review has happened.

**Comment by appakz** [comment]
Also, this PR is backwards right? It should have been to merge Development into master, not the other way around. I'll open another one here in a sec

**Comment by jamescrowley321** [comment]
Apologies, meant to merge the master changes into the PR.



From: Jesse Taber

Sent: Tuesday, February 9, 8:48 PM

Subject: Re: [event-site] First Round of Changes (#29)

To: TallyDotNet/event-site

Cc: jamescrowley321



Also, for future reference the PR doesn't typically get merged into master until after the review has happened.

**Pull request merged**
